# Generated by Django 4.2.30 on 2026-05-25 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URLScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('verdict', models.CharField(choices=[('SAFE', 'Safe'), ('SUSPICIOUS', 'Suspicious'), ('PHISHING', 'Phishing')], default='SAFE', max_length=16)),
                ('threat_score', models.FloatField(default=0.0, help_text='0.0 – 100.0')),
                ('features', models.JSONField(blank=True, default=dict)),
                ('network', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('pdf_path', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='scanner.urlscan')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=8)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='scanner.urlscan')),
            ],
        ),
        migrations.AddIndex(
            model_name='urlscan',
            index=models.Index(fields=['verdict'], name='scanner_url_verdict_9f38ab_idx'),
        ),
        migrations.AddIndex(
            model_name='urlscan',
            index=models.Index(fields=['-created_at'], name='scanner_url_created_1b22c4_idx'),
        ),
    ]
